version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://user:password@db/crypto
      REDIS_HOST: redis

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: krypto
      POSTGRES_PASSWORD: krypto
      POSTGRES_DB: krypto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
